firstBucketName="m347-testbucketnr1"
secondBucketName="m347-testbucketnr2"
functionName="m347-function"
runtime="bash"
roleARN="arn:aws:iam::341124230193:role/LabRole"
code="S3Bucket=string,S3Key=string,S3ObjectVersion=string,ImageUri=string"
# lambdaPolicySource="lambdaPolicy.json"